repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: go-fmt
        name: run go format in datetimegin(go fmt)
        language: system
        entry: bash -c 'cd datetimegin && exec go fmt ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimegin/
      - id: go-fmt
        name: run go format in datetimehttp(go fmt)
        language: system
        entry: bash -c 'cd datetimehttp && exec go fmt ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimehttp/
      - id: golangci-lint
        name: run go lint(golangci-lint) in datetimegin
        language: system
        entry: bash -c 'cd datetimegin && exec golangci-lint run ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimegin/
      - id: golangci-lint
        name: run go lint(golangci-lint) in datetimehttp
        language: system
        entry: bash -c 'cd datetimehttp && exec golangci-lint run ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimehttp/
      - id: go-unit-tests
        name: run go test s(go test) in datetimegin
        language: system
        entry: bash -c 'cd datetimegin && exec go test ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimegin/
      - id: go-unit-tests
        name: run go test s(go test) in datetimehttp
        language: system
        entry: bash -c 'cd datetimehttp && exec go test ./...'
        pass_filenames: false
        types: [go]
        files: ^datetimehttp/
