FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/datetimegin ./cmd/datetimegin
COPY ./pkg/datetimegin ./pkg/datetimegin

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main ./cmd/datetimegin


FROM scratch AS datetimeginimg

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
