version: "3"
services:
  datetimegin:
    build:
      context: .
      dockerfile: Dockerfile.gin
      target: datetimeginimg
    ports:
      - "5000:8080"

  datetimehttp:
    build:
      context: .
      dockerfile: Dockerfile.http
      target: datetimehttpimg
    ports:
      - "3000:8080"
