FROM golang:1.22 AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/datetimehttp ./cmd/datetimehttp
COPY ./pkg/datetimehttp ./pkg/datetimehttp

ENV PORT=8080

RUN go build -o main ./cmd/datetimehttp


FROM scratch AS datetimehttpimg

WORKDIR /

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
