FROM golang:1.22

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./cmd/datetimegin ./cmd/datetimegin
COPY ./pkg/datetimegin ./pkg/datetimegin

ENV PORT=8080

RUN go build -o main ./cmd/datetimegin

EXPOSE 8080

CMD ["./main"]
