name: Go Test

on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22.4"

      - name: Run go fmt
        run: |
          cd datetimegin && go fmt ./...
          cd ../datetimehttp && go fmt ./...
          git diff --exit-code || (echo "Formatting issues found. Please run 'go fmt'." && exit 1)

      - name: Run golangci-lint in datetimegin
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          working-directory: datetimegin

      - name: Run golangci-lint in datetimehttp
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          working-directory: datetimehttp

      - name: Test
        run: |
          cd datetimegin && go test -v ./...
          cd ../datetimehttp && go test -v ./...
